version: '3.8'

services:
  mqtt:
    image: thmork/st4-mqtt:latest
    ports:
      - 9001:9001
      - 1883:1883
    networks:
      - spring-network

  st4-agv:
    image: thmork/st4-agv:latest
    ports:
      - 8082:80
    networks:
      - spring-network

  st4-warehouse:
    image: thmork/st4-warehouse:latest
    ports:
      - 8081:80
    networks:
      - spring-network

  st4-assemblystation:
    image: thmork/st4-assemblystation:latest
    environment:
      MQTT_TCP_CONNECTION_HOST: "mqtt"
      MQTT_TCP_CONNECTION_PORT: 9001
    networks:
      - spring-network

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: kodeord1
      MYSQL_DATABASE: warehouse_db
    ports:
      - "3306:3306"
    networks:
      - spring-network

  spring-app:
    build: .
    container_name: spring-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_PROFILES_ACTIVE: dev
    networks:
      - spring-network

networks:
  spring-network:
